#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  3 09:22:04 2022
@author: hussain
"""

import os
import json

path = 'E:/hussain/data/ROBIN_OOD/full_dataset/phase-1'
print(os.path.exists(path))
filename = 'nuisance2filenames.json'
file_path = os.path.join(path, filename)
print(os.path.isfile(file_path))

with open (file_path, 'r') as file:
    data = json.load(file)
    
print(data.keys()) # dict_keys(['context', 'texture', 'shape', 'pose', 'weather'])

print(data['shape'])
