#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  3 09:22:04 2022
@author: hussain
"""

import os
import json
import shutil

path = 'E:/hussain/data/ROBIN_OOD/full_dataset/phase-1'
print(os.path.exists(path))
filename = 'nuisance2filenames.json'
file_path = os.path.join(path, filename)
print(os.path.isfile(file_path))

with open (file_path, 'r') as file:
    data = json.load(file)
    
print(data.keys()) # dict_keys(['context', 'texture', 'shape', 'pose', 'weather'])

#print(data['shape'])

temp_path = os.path.join(path, 'temp')

for nuisance in (data.keys()):
    os.makedirs(os.path.join(temp_path, nuisance), exist_ok = True)
    nuisance_path = os.path.join(temp_path, nuisance)
    
    for img_name in (data[nuisance]):
        data_source_path = os.path.join(path, 'images')
        img_copy_path = os.path.join(data_source_path, img_name)
        img_dest_path = os.path.join(nuisance_path, img_name)
        print('source path: ', img_copy_path, ' ::: destination path: ', img_dest_path)
        shutil.copyfile(img_copy_path, img_dest_path) 
    
